### PR TITLE
fix TwitterSource username bug, add Gnews proxy

### PR DESCRIPTION
**Pull request by chxlium**

### CODE REVIEW

**Comment by GirishPatel** [comment]
@chxlium thanks for your contribution!
Please add a commented line for config argument in example and documentation also. This will help others to know how to provide **proxy** config.

- https://github.com/obsei/obsei/blob/master/README.md?plain=1#L580
- https://github.com/obsei/obsei/blob/master/example/google_news_example.py#L20

**Comment by lalitpagaria** [comment]
@chxlium Thank you for your contribution. Please address the comment as suggested by @GirishPatel and I will merge this PR.

Tests are failing but it is something else which we will fix.

**Comment by chxlium** [comment]
@GirishPatel @lalitpagaria Yeah sure! Sorry about that!

**Comment by GirishPatel** [comment]
@chxlium changes looks good to me.
For fixing build failure, pull latest master into your branch. 
Also, please sign [CLA](https://github.com/obsei/obsei/pull/244#issuecomment-1139420748).

**Comment by chxlium** [comment]
@GirishPatel Hey, I already merged with the latest master.
I am sorry about the CLA sign, I tried last Friday, Sunday, and today but it all failed, from the error I think it has something to do with my username?

**Comment by GirishPatel** [comment]
> Chenxi Liu

You did commit from different accounts - **Chenxi Liu** and **chxlium**.
**Chenxi Liu** is not registered on github. 

I guess the easier way is to create another branch with commits only from **chxlium**, and then raise another PR. We'll be able to merge then.

**Comment by GirishPatel** [comment]
Closing PR as changes has been addressed by https://github.com/obsei/obsei/pull/246

**Pull request closed without merging**
